# Site settings
title: Kickback
description: >
  Kickback is a online media company that primarily focuses on creative content and audience growth.
  We are here to help content creators like yourself to reach a larger audience on YouTube and produce quality content.
  Kickback is a collaborative home for amazing personalities and original content.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gokickback.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
